import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { FileText, FileDown } from 'lucide-react';
import { toast } from 'sonner';

interface ExportFormatDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  report: {
    content: string;
    report_type: string;
    created_at: string;
  };
}

export default function ExportFormatDialog({
  open,
  onOpenChange,
  report,
}: ExportFormatDialogProps) {
  const filename = `${report.report_type}-${new Date(report.created_at).toISOString().split('T')[0]}`;

  const handleMarkdownExport = () => {
    const blob = new Blob([report.content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${filename}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success('Markdown file downloaded');
    onOpenChange(false);
  };

  const handlePdfExport = () => {
    // Create a printable window with styled content
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      toast.error('Please allow popups to export as PDF');
      return;
    }

    const formattedDate = new Date(report.created_at).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });

    const reportTitle = report.report_type
      .split('_')
      .map(word => word.charAt(0).toUpperCase() + word.slice(1))
      .join(' ');

    // Convert markdown to basic HTML
    const htmlContent = report.content
      .replace(/^### (.*$)/gm, '<h3>$1</h3>')
      .replace(/^## (.*$)/gm, '<h2>$1</h2>')
      .replace(/^# (.*$)/gm, '<h1>$1</h1>')
      .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
      .replace(/\*(.*?)\*/g, '<em>$1</em>')
      .replace(/^- (.*$)/gm, '<li>$1</li>')
      .replace(/(<li>.*<\/li>\n?)+/g, '<ul>$&</ul>')
      .replace(/\n\n/g, '</p><p>')
      .replace(/\n/g, '<br>');

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>${reportTitle} - ${formattedDate}</title>
          <style>
            @media print {
              body { margin: 0; }
            }
            body {
              font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
              line-height: 1.6;
              color: #1a1a1a;
              max-width: 800px;
              margin: 0 auto;
              padding: 40px 20px;
            }
            .header {
              border-bottom: 2px solid #e5e5e5;
              padding-bottom: 20px;
              margin-bottom: 30px;
            }
            .header h1 {
              margin: 0 0 8px 0;
              font-size: 28px;
              font-weight: 600;
            }
            .header .date {
              color: #666;
              font-size: 14px;
            }
            .content h1 { font-size: 24px; margin-top: 24px; }
            .content h2 { font-size: 20px; margin-top: 20px; color: #333; }
            .content h3 { font-size: 16px; margin-top: 16px; color: #444; }
            .content p { margin: 12px 0; }
            .content ul { margin: 12px 0; padding-left: 24px; }
            .content li { margin: 6px 0; }
            .content strong { font-weight: 600; }
            .footer {
              margin-top: 40px;
              padding-top: 20px;
              border-top: 1px solid #e5e5e5;
              font-size: 12px;
              color: #999;
            }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>${reportTitle}</h1>
            <div class="date">Generated on ${formattedDate}</div>
          </div>
          <div class="content">
            <p>${htmlContent}</p>
          </div>
          <div class="footer">
            Generated by Axis Systems
          </div>
        </body>
      </html>
    `);
    printWindow.document.close();
    
    // Wait for content to load, then trigger print
    printWindow.onload = () => {
      printWindow.print();
    };
    
    toast.success('Opening print dialog for PDF');
    onOpenChange(false);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>Export Report</DialogTitle>
          <DialogDescription>
            Choose a format to export your report.
          </DialogDescription>
        </DialogHeader>

        <div className="grid gap-3 py-4">
          <Button
            variant="outline"
            className="h-auto p-4 justify-start"
            onClick={handleMarkdownExport}
          >
            <FileText className="h-5 w-5 mr-3 text-muted-foreground" />
            <div className="text-left">
              <div className="font-medium">Markdown (.md)</div>
              <div className="text-xs text-muted-foreground">
                Plain text with formatting. Great for docs and notes.
              </div>
            </div>
          </Button>
          
          <Button
            variant="outline"
            className="h-auto p-4 justify-start"
            onClick={handlePdfExport}
          >
            <FileDown className="h-5 w-5 mr-3 text-muted-foreground" />
            <div className="text-left">
              <div className="font-medium">PDF</div>
              <div className="text-xs text-muted-foreground">
                Print-ready format. Uses your browser's print dialog.
              </div>
            </div>
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
